Document: goldpieces
Title: Debian goldpieces Manual
Author: <insert document author here>
Abstract: This manual describes what goldpieces is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/goldpieces/goldpieces.sgml.gz

Format: postscript
Files: /usr/share/doc/goldpieces/goldpieces.ps.gz

Format: text
Files: /usr/share/doc/goldpieces/goldpieces.text.gz

Format: HTML
Index: /usr/share/doc/goldpieces/html/index.html
Files: /usr/share/doc/goldpieces/html/*.html
